### PR TITLE
Remove registration of unused hook

### LINKED ISSUE #23708: Customer Data Privacy module
#### Describe the bug

The module Customer data privacy are default installed in the version 1.7.7.2
But that module aren't need with the module GDPR installed.
When you uninstall the module Customer Data Privacy this give you one error and don't uninstall

#### Expected behavior

Delete the module without problem

#### Steps to Reproduce

1. Go to 'modules in prestashop 1.7.7.2 clean install'
2. Click on 'data privacy costomer'
3. select delete

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Deletion of unused hook, it is necessary because from Prestashop 1.7.8 all registered hooks in module must have a corresponding listener, otherwise they won't install in dev mode.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Partly fixes #19230 & fixes https://github.com/PrestaShop/PrestaShop/issues/23708
| How to test?  | Test that module can still be installed without any problem

### CODE REVIEW

File: upgrade/upgrade-2-1-0.php [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA
+ * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+if (!defined('_PS_VERSION_')) {
+    exit;
+}
+function upgrade_module_2_1_0($object)
```
Comment (matthieu-rolland) [inline upgrade/upgrade-2-1-0.php:29]: I added an upgrade script, but I didn't upgrade the module, since this is not a release pull request, but maybe this PR could be a release PR directly ?

File: ps_dataprivacy.php [hunk 2]
```diff
@@ -56,14 +56,12 @@ public function install()
...
         return (parent::install()
             && $this->registerHook('additionalCustomerFormFields')
-            && $this->registerHook('actionSubmitAccountBefore')
             && $this->installFixtures());
     }
 
     public function uninstall()
     {
         return ($this->unregisterHook('additionalCustomerFormFields')
-            && $this->unregisterHook('actionBeforeSubmitAccount')
```
Comment (matthieu-rolland) [inline ps_dataprivacy.php:79]: `actionSubmitAccountBefore` and `actionBeforeSubmitAccount` are actually the same hook (alias)

File: upgrade/upgrade-2-1-0.php (hunk 1 above)
Comment (PierreRambaud) [reply upgrade/upgrade-2-1-0.php:29]: You can upgrade the number in this pull request.

Comment (matthieu-rolland) [reply upgrade/upgrade-2-1-0.php:29]: done :+1:

File: ps_dataprivacy.php [hunk 3]
```diff
@@ -36,7 +36,7 @@ public function __construct()
     {
         $this->name = 'ps_dataprivacy';
         $this->author = 'PrestaShop';
-        $this->version = '2.0.0';
+        $this->version = '2.1.0';
```
Comment (Progi1984) [inline ps_dataprivacy.php:39]:
```suggestion
        $this->version = '2.0.0';
```

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]
I think QA can be performed by devs for this module

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional OK pour QA by dev ?

**Comment by Robin-Fischer-PS** [comment]
Yes @Progi1984 , OK for a QA by dev :)

**Comment by Progi1984** [comment]
@matthieu-rolland Need rebase

**Review by Progi1984 — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @matthieu-rolland !

Tested :

- Uninstall the module : :heavy_check_mark: 
- Install the module : :heavy_check_mark: 

Regression test :
- Configuration of the module (change message in different language) : :heavy_check_mark: 
- Disable the module : :heavy_check_mark: 
- Enable the module :  :heavy_check_mark: 


So it's QA :heavy_check_mark: 

Thanks !

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland  & @Robin-Fischer-PS

**Comment by alfonsolr09** [comment]
When will this module update be released? @PierreRambaud @Progi1984 @matthieu-rolland
